// Canonical TypeScript contract mirroring src/schemas/agent_state.py (Pydantic).
// Keep this in sync with the backend schema; lib/schema.ts guards against drift.

export type AgentRole = 'contracting_authority' | 'aggrieved_bidder' | 'court';

export interface DisputeScenario {
  dispute_id: string;
  title: string;
  description: string;
  contract_value_gbp: number;
  dispute_type: string;
  procedural_stage: string;
  contracting_authority_name: string;
  bidder_name: string;
}

export interface PreNegotiationStatement {
  role: AgentRole;
  interests: string[];
  goals: string[];
  batna: string;
  opening_position: string;
  legal_basis: string[];
  confidence_score: number; // 0-1
}

export interface NegotiationMessage {
  round_number: number;
  sender_role: AgentRole;
  message: string;
  proposal: string | null;
  concession_made: string | null;
}

export interface ComplianceAssessment {
  round_number: number;
  process_followed: boolean;
  manifest_error_found: boolean;
  applicable_provisions: string[];
  reasoning: string;
  // Free string, not a strict union — LLM output varies. Known values in practice:
  // "continue negotiation" | "re-evaluation" | "no remedy - decision stands" | "damages"
  recommended_action: string;
  deadlock: boolean;
}

export interface WinStatement {
  role: AgentRole;
  outcome_relative_to_batna: string;
  win_statement: string;
  what_was_achieved: string[];
  what_was_conceded: string[];
}

export interface NegotiationSummary {
  key_sticking_points: string[];
  concessions_summary: string;
  court_reasoning_summary: string;
  likely_next_steps: string;
  plain_english_summary: string;
}

export interface NegotiationState {
  scenario: DisputeScenario;
  round_number: number;
  max_rounds: number;
  ca_pre_negotiation: PreNegotiationStatement | null;
  bidder_pre_negotiation: PreNegotiationStatement | null;
  messages: NegotiationMessage[];
  compliance_checks: ComplianceAssessment[];
  resolved: boolean;
  resolution_outcome: string | null;
  adjudicated: boolean;
  ca_win_statement: WinStatement | null;
  bidder_win_statement: WinStatement | null;
  summary: NegotiationSummary | null;
}

export interface BatchIndividualRun {
  run_number: number;
  resolved: boolean | null;
  outcome: string | null;
  rounds_taken: number | null;
  manifest_error_found_any_round: boolean | null;
  manifest_error_rounds: number[];
  process_not_followed_any_round: boolean | null;
  duration_seconds: number;
  error: string | null; // non-null only on failed runs
}

export interface BatchMetrics {
  // Renamed from agreement_rate (Aug 2026): this measures whether the negotiation
  // resolved without deadlock, not whether the parties agreed with each other.
  resolution_rate: number | null;
  deadlock_rate: number | null;
  manifest_error_detection_rate: number | null;
  average_rounds_to_conclusion: number;
  average_duration_seconds: number;
  outcome_distribution: Record<string, number>;
}

/** Structural-compliance counters — how much repair the LLM's output needed. */
export interface BatchCompliance {
  structured_responses: number;
  clean_responses: number;
  /** clean_responses / structured_responses, in [0,1]. */
  structural_compliance_rate: number | null;
  json_fallbacks: number;
  field_coercions: number;
  parse_failures: number;
  repetition_retries: number;
}

export interface BatchSummary {
  scenario_id: string;
  scenario_title: string;
  n_runs_requested: number;
  n_runs_successful: number;
  n_runs_failed: number;
  max_rounds: number;
  timestamp: string; // "20260726_230957"
  metrics: BatchMetrics;
  individual_runs: BatchIndividualRun[];

  // Added Aug 2026. All optional: batches produced before this exist in
  // batch_results/ without them and must still load.
  /** False when the batch was killed part-way. Never cite figures from these. */
  complete?: boolean;
  n_runs_completed_so_far?: number;
  /** "V3" | "V4" — which Court prompt this batch ran under. */
  court_prompt_version?: string;
  contracting_authority?: string;
  bidder?: string;
  compliance?: BatchCompliance;
}

// -- manifest.json (generated by scripts/sync-data.mjs) --

export interface ManifestCaseEntry {
  id: string;
  source: 'root';
  file: string;
  scenarioId: string;
  title: string;
  timestamp: string; // ISO
  timestampSource: 'file-mtime';
  resolved: boolean;
  outcome: string | null;
  roundsTaken: number;
  maxRounds: number;
  isRealCase: boolean;
}

export interface ManifestBatchRun {
  runNumber: number;
  resolved: boolean | null;
  outcome: string | null;
  roundsTaken: number | null;
  manifestErrorFoundAnyRound: boolean | null;
  hasTranscript: boolean;
  file: string | null;
  error: string | null;
}

export interface ManifestBatchEntry {
  id: string;
  dir: string;
  scenarioId: string;
  scenarioTitle: string;
  timestamp: string; // raw "20260726_230957"
  timestampIso: string;
  nRunsRequested: number;
  nRunsSuccessful: number;
  nRunsFailed: number;
  maxRounds: number;
  metrics: BatchMetrics;
  runs: ManifestBatchRun[];

  // Added Aug 2026 — nulled for batches generated before these existed.
  /** False when the batch was killed part-way; the UI must label these. */
  complete: boolean | null;
  /** "V3" | "V4" — lets the picker tell the Court-prompt ablation arms apart. */
  courtPromptVersion: string | null;
  structuralComplianceRate: number | null;
}

export interface Manifest {
  generatedAt: string;
  cases: ManifestCaseEntry[];
  batches: ManifestBatchEntry[];
}

// -- src/risk/challenge_risk.py (pre-award challenge risk screen) --

/** Mirrors CAProfile in src/schemas/agent_state.py — only the fields the risk-screen UI exposes. */
export interface CAProfileInput {
  documentation_quality?: 'robust' | 'partial' | 'weak';
  panel_capability?: 'procurement_trained' | 'mixed' | 'technical_untrained';
  internal_accountability_exposure?: 'low' | 'medium' | 'high';
}

/** Mirrors BidderProfile — only the fields the risk-screen UI exposes. */
export interface BidderProfileInput {
  score_margin?: 'narrow' | 'moderate' | 'wide';
  feedback_quality_received?: 'detailed' | 'adequate' | 'minimal';
  incumbent?: boolean;
  market_conditions?: 'buoyant' | 'normal' | 'slow';
}

export interface RiskFlag {
  category: string;
  field: string;
  severity: 'low' | 'medium' | 'high';
  confidence: 'known' | 'estimated';
  rationale: string;
  mitigation: string;
}

export interface ChallengeRiskAssessment {
  overall_risk_band: 'low' | 'medium' | 'high';
  risk_score: number;
  flags: RiskFlag[];
  summary: string;
}

// -- src/recommendation/settlement_recommendation.py --

export interface DissentingOutcome {
  outcome: string;
  n_runs: number;
  share: number;
}

export interface SettlementRecommendation {
  scenario_id: string;
  scenario_title: string;
  n_runs: number;
  modal_outcome: string;
  modal_outcome_meaning: string;
  confidence: number;
  dissenting_outcomes: DissentingOutcome[];
  resolution_rate: number | null;
  average_rounds_to_conclusion: number;
  rationale: string;
  sample_size_caveat: string | null;
  framing_caveat: string;
}

export interface BatchListEntry {
  batch_id: string;
  scenario_id: string;
  scenario_title: string;
  court_prompt_version: string | null;
  n_runs: number;
}
