// Canonical TypeScript contract mirroring src/schemas/agent_state.py (Pydantic).
// Keep this in sync with the backend schema; lib/schema.ts guards against drift.

export type AgentRole = 'contracting_authority' | 'aggrieved_bidder' | 'court';

export interface DisputeScenario {
  dispute_id: string;
  title: string;
  description: string;
  contract_value_gbp: number;
  dispute_type: string;
  procedural_stage: string;
  contracting_authority_name: string;
  bidder_name: string;
}

export interface PreNegotiationStatement {
  role: AgentRole;
  interests: string[];
  goals: string[];
  batna: string;
  opening_position: string;
  legal_basis: string[];
  confidence_score: number; // 0-1
}

export interface NegotiationMessage {
  round_number: number;
  sender_role: AgentRole;
  message: string;
  proposal: string | null;
  concession_made: string | null;
}

export interface ComplianceAssessment {
  round_number: number;
  process_followed: boolean;
  manifest_error_found: boolean;
  applicable_provisions: string[];
  reasoning: string;
  // Free string, not a strict union — LLM output varies. Known values in practice:
  // "continue negotiation" | "re-evaluation" | "no remedy - decision stands" | "damages"
  recommended_action: string;
  deadlock: boolean;
}

export interface WinStatement {
  role: AgentRole;
  outcome_relative_to_batna: string;
  win_statement: string;
  what_was_achieved: string[];
  what_was_conceded: string[];
}

export interface NegotiationSummary {
  key_sticking_points: string[];
  concessions_summary: string;
  court_reasoning_summary: string;
  likely_next_steps: string;
  plain_english_summary: string;
}

export interface NegotiationState {
  scenario: DisputeScenario;
  round_number: number;
  max_rounds: number;
  ca_pre_negotiation: PreNegotiationStatement | null;
  bidder_pre_negotiation: PreNegotiationStatement | null;
  messages: NegotiationMessage[];
  compliance_checks: ComplianceAssessment[];
  resolved: boolean;
  resolution_outcome: string | null;
  adjudicated: boolean;
  ca_win_statement: WinStatement | null;
  bidder_win_statement: WinStatement | null;
  summary: NegotiationSummary | null;
}

export interface BatchIndividualRun {
  run_number: number;
  resolved: boolean | null;
  outcome: string | null;
  rounds_taken: number | null;
  manifest_error_found_any_round: boolean | null;
  manifest_error_rounds: number[];
  process_not_followed_any_round: boolean | null;
  duration_seconds: number;
  error: string | null; // non-null only on failed runs
}

export interface BatchMetrics {
  agreement_rate: number | null;
  deadlock_rate: number | null;
  manifest_error_detection_rate: number | null;
  average_rounds_to_conclusion: number;
  average_duration_seconds: number;
  outcome_distribution: Record<string, number>;
}

export interface BatchSummary {
  scenario_id: string;
  scenario_title: string;
  n_runs_requested: number;
  n_runs_successful: number;
  n_runs_failed: number;
  max_rounds: number;
  timestamp: string; // "20260726_230957"
  metrics: BatchMetrics;
  individual_runs: BatchIndividualRun[];
}

// -- manifest.json (generated by scripts/sync-data.mjs) --

export interface ManifestCaseEntry {
  id: string;
  source: 'root';
  file: string;
  scenarioId: string;
  title: string;
  timestamp: string; // ISO
  timestampSource: 'file-mtime';
  resolved: boolean;
  outcome: string | null;
  roundsTaken: number;
  maxRounds: number;
  isRealCase: boolean;
}

export interface ManifestBatchRun {
  runNumber: number;
  resolved: boolean | null;
  outcome: string | null;
  roundsTaken: number | null;
  manifestErrorFoundAnyRound: boolean | null;
  hasTranscript: boolean;
  file: string | null;
  error: string | null;
}

export interface ManifestBatchEntry {
  id: string;
  dir: string;
  scenarioId: string;
  scenarioTitle: string;
  timestamp: string; // raw "20260726_230957"
  timestampIso: string;
  nRunsRequested: number;
  nRunsSuccessful: number;
  nRunsFailed: number;
  maxRounds: number;
  metrics: BatchMetrics;
  runs: ManifestBatchRun[];
}

export interface Manifest {
  generatedAt: string;
  cases: ManifestCaseEntry[];
  batches: ManifestBatchEntry[];
}
