"""
Settlement recommendation synthesizer — a deliberately SCOPED version of what was floated to Phil.

WHY SCOPED: the fuller version discussed earlier (dual-acceptance simulation, expert-panel-validated
recommendations, confidence bounds from a purpose-built Monte Carlo) is genuinely a separate, large piece
of work — evaluation-layer work, not a module to build in one sitting. It's also secondary to the risk
screen (src/risk/challenge_risk.py): a settlement recommendation operates on a dispute that has already
started, whereas the risk screen is actual prevention, which is what Phil said the heart of the project
was. Build order matters here.

WHAT THIS ACTUALLY IS: a thin, honest synthesis layer over a batch you've already run. `run_batch_evaluation.py`
already produces an outcome distribution across N repeated runs of the same scenario — that distribution
*is* the Monte Carlo sample; it was previously only used as noise to average away for an accuracy metric.
This module reframes the same data as a recommendation: the modal outcome, a confidence figure derived from
how often the runs agreed, and — the part that matters most honestly — the DISSENTING outcomes named
explicitly rather than silently averaged into the majority.

CONSTRAINED VOCABULARY — do not extend this without reading Doc 3 first. Fisher & Ury's principled-negotiation
material (Doc 3, cluster A) states explicitly: "In procurement award-stage disputes... you cannot 'split the
difference' or renegotiate award outcomes." This module NEVER invents a settlement figure or a compromise
outcome. It only ever reports outcomes that are literally in the Court agent's own recommended_action
vocabulary (src/prompts/court_prompt.py) or the orchestrator's deadlock string — the same constrained,
legally-grounded remedy set the simulation itself is allowed to reach. If a batch ever contains an outcome
string outside `KNOWN_OUTCOMES`, `synthesize_recommendation` raises rather than silently reporting it — that
would mean the Court prompt's vocabulary drifted without this module being updated to match, and an
unrecognised "settlement" is exactly the kind of fabrication this whole project's discipline exists to catch.

FRAMING — this is the same caveat the risk screen carries, restated for a different audience: this is
non-binding decision support, framed as a computational Early Neutral Evaluation (a real, TCC-adjacent
process, not an invented category) — not legal advice, and not an oracle. A tool that hands both parties a
settlement figure invites a fair "is this practising law" question; naming the process it's modelling on is
the honest answer to that question, not a disclaimer bolted on afterward.

WHAT IS DELIBERATELY NOT BUILT HERE: an LLM-generated narrative (terms for the CA specifically, terms for
the bidder specifically, a prose rationale reading the actual round transcripts rather than just the
aggregate stats). That needs a model call — a "recommendation agent" reading N full transcripts, analogous
to the Summary agent but operating across a whole batch rather than within one run — and was deliberately
deferred so this module could be built and verified without touching Ollama while the Court-prompt
ablation was running. `rationale` below is generated by string templating over the aggregate numbers, not
by an LLM, and says so.
"""

from collections import Counter

from pydantic import BaseModel, Field

# The Court agent's own documented vocabulary (src/prompts/court_prompt.py "YOUR POSSIBLE RECOMMENDED
# ACTIONS") plus the orchestrator's deadlock string (src/graph_orchestrator.py::court_check_node). This is
# the ENTIRE set of outcomes this module will ever report — see module docstring.
KNOWN_OUTCOMES = {
    "continue negotiation",
    "re-evaluation",
    "no remedy - decision stands",
    "damages",
    "deadlock - max rounds reached, escalate to formal proceedings",
}

# Below this many successful runs, `confidence` is flagged rather than presented at face value — found in
# a manual audit 15 Aug 2026: a batch with n=1 produced confidence=1.0 with nothing distinguishing it from
# a genuinely well-replicated result. 5 is chosen so the n=4 batches already on disk from earlier in this
# project (superseded by n=8 re-runs for the final ablation table, but still reachable via the API if
# pointed at an old batch_id) are correctly flagged, while the current n=8 batches are not.
SMALL_SAMPLE_THRESHOLD = 5

_OUTCOME_MEANING = {
    "re-evaluation": "the Court found (or the evidence supports) a manifest error; the authority should "
                      "redo the scoring for the disputed criterion",
    "no remedy - decision stands": "the process was compliant and independently verified, or rationally "
                                    "justified; the challenge does not succeed",
    "damages": "a process failure was found, but re-running the procurement is impractical; a damages "
               "remedy is indicated instead",
    "continue negotiation": "no clear compliance issue was found after independent verification; the "
                             "matter was still open when the run concluded",
    "deadlock - max rounds reached, escalate to formal proceedings": "no resolution was reached within the "
                                                                      "simulated negotiation; the real-world "
                                                                      "equivalent is formal TCC proceedings",
}


class DissentingOutcome(BaseModel):
    outcome: str
    n_runs: int
    share: float = Field(ge=0.0, le=1.0)


class SettlementRecommendation(BaseModel):
    """
    Synthesized from a completed batch (see synthesize_recommendation). Deliberately NOT a single number or
    a single sentence — a defensible recommendation needs to show its dissent, not hide it.
    """

    scenario_id: str
    scenario_title: str
    n_runs: int = Field(description="Successful runs the recommendation is based on")
    modal_outcome: str = Field(description="The most frequent outcome across runs — from KNOWN_OUTCOMES only")
    modal_outcome_meaning: str
    confidence: float = Field(ge=0.0, le=1.0, description="Share of successful runs that reached modal_outcome")
    dissenting_outcomes: list[DissentingOutcome] = Field(
        description="Every OTHER outcome that occurred, named explicitly rather than averaged away"
    )
    resolution_rate: float | None
    average_rounds_to_conclusion: float
    rationale: str = Field(description="Template-generated from the aggregate stats — NOT an LLM narrative. See module docstring.")
    sample_size_caveat: str | None = Field(
        default=None,
        description="Populated when n_runs is below SMALL_SAMPLE_THRESHOLD — confidence/modal_outcome from "
                    "a handful of runs should be read as indicative, not stable. None when the batch clears "
                    "the threshold.",
    )
    framing_caveat: str = Field(
        default=(
            "Non-binding decision support, modelled on Early Neutral Evaluation (ENE) — a real, "
            "TCC-adjacent process — not legal advice and not a settlement offer. Constrained to the same "
            "remedy vocabulary the Court agent itself uses (Doc 3: award-stage disputes cannot be settled "
            "by splitting the difference). Not yet validated against real settlement outcomes — see "
            "CLAUDE.md 'client actions' for the anonymised-data ask that would let this be measured rather "
            "than only documented."
        )
    )


def synthesize_recommendation(batch_summary: dict) -> SettlementRecommendation:
    """
    Pure aggregation over an already-completed batch_summary.json (as loaded by json.load — the same dict
    shape tests/run_batch_evaluation.py writes). No LLM call.

    Raises ValueError if the batch is incomplete (complete=False) or empty of successful runs — citing an
    incomplete batch as the basis for a recommendation is exactly the mistake the `complete` flag exists to
    catch (see CLAUDE.md: "Never cite figures from a summary with complete: false").
    """
    # `complete` was added 15 Aug 2026 (see CLAUDE.md); batches from before that date don't carry the key
    # at all. An explicit `complete: false` always blocks — that's a batch we KNOW was killed mid-run. An
    # ABSENT key falls back to the completion signal that always existed: n_runs_successful/n_runs_failed
    # summing to n_runs_requested means every requested run finished (successfully or not) before the
    # batch_summary.json was written, which is what "complete" meant before the flag existed. Refusing the
    # entire pre-flag historical corpus over a field that didn't exist yet would be overzealous, not careful.
    complete_flag = batch_summary.get("complete")
    if complete_flag is False:
        raise ValueError(
            f"Refusing to synthesize a recommendation from an incomplete batch "
            f"({batch_summary.get('n_runs_completed_so_far', '?')}/{batch_summary.get('n_runs_requested', '?')} "
            f"runs) — see CLAUDE.md: never cite figures from a summary with complete: false."
        )
    if complete_flag is None:
        n_req = batch_summary.get("n_runs_requested")
        n_done = batch_summary.get("n_runs_successful", 0) + batch_summary.get("n_runs_failed", 0)
        if n_req is None or n_done != n_req:
            raise ValueError(
                f"Batch predates the 'complete' flag and its run counts don't confirm completion "
                f"({n_done}/{n_req} accounted for) — refusing rather than guessing."
            )

    runs = batch_summary.get("individual_runs", [])
    successful = [r for r in runs if r.get("error") is None and r.get("outcome") is not None]
    if not successful:
        raise ValueError("Batch has no successful runs to synthesize a recommendation from.")

    outcomes = Counter(r["outcome"] for r in successful)
    unknown = set(outcomes) - KNOWN_OUTCOMES
    if unknown:
        raise ValueError(
            f"Batch contains outcome(s) outside the known vocabulary: {sorted(unknown)}. This means "
            f"court_prompt.py's recommended_action vocabulary (or the orchestrator's deadlock string) has "
            f"drifted without KNOWN_OUTCOMES in this module being updated to match — fix that before "
            f"synthesizing, rather than silently reporting an outcome this module doesn't recognise."
        )

    n = len(successful)
    modal_outcome, modal_count = outcomes.most_common(1)[0]
    confidence = round(modal_count / n, 4)

    dissenting = [
        DissentingOutcome(outcome=o, n_runs=c, share=round(c / n, 4))
        for o, c in outcomes.most_common() if o != modal_outcome
    ]

    metrics = batch_summary.get("metrics", {})
    resolution_rate = metrics.get("resolution_rate", metrics.get("agreement_rate"))

    rationale_bits = [
        f"Across {n} independent simulated negotiations of this scenario, "
        f"{modal_count}/{n} ({confidence:.0%}) reached '{modal_outcome}' "
        f"({_OUTCOME_MEANING.get(modal_outcome, 'outcome meaning not documented')})."
    ]
    if dissenting:
        diss_desc = "; ".join(f"{d.n_runs}/{n} ({d.share:.0%}) reached '{d.outcome}'" for d in dissenting)
        rationale_bits.append(
            f"Not every run agreed: {diss_desc}. This disagreement is itself informative — a scenario "
            f"where every run converges on the same outcome supports a confident recommendation; one with "
            f"substantial dissent (as here, if the dissenting share is large) suggests the underlying "
            f"dispute is more genuinely contestable than a single verdict would imply."
        )
    else:
        rationale_bits.append("Every successful run reached the same outcome — no dissent in this sample.")
    rationale_bits.append(
        f"Average rounds to conclusion: {metrics.get('average_rounds_to_conclusion', '?')}."
    )

    sample_size_caveat = None
    if n < SMALL_SAMPLE_THRESHOLD:
        sample_size_caveat = (
            f"Based on only {n} successful run(s) — below the {SMALL_SAMPLE_THRESHOLD}-run threshold this "
            f"module treats as a stable sample. A {confidence:.0%} confidence figure from {n} run(s) is "
            f"barely more than an anecdote: at this sample size, a single differently-seeded run could "
            f"change the modal outcome entirely. Re-run with more repetitions before treating this as more "
            f"than a single illustrative data point — this is a distinct concern from the framing caveat "
            f"below, which is about real-world validation, not sample size."
        )
        # Folded into rationale too (not just the dedicated field) so a caller reading only `rationale`
        # still sees it — the dedicated field exists for a UI that wants to style it distinctly, same
        # reasoning as why dissenting outcomes get both a rationale sentence and their own list field.
        rationale_bits.append(sample_size_caveat)

    return SettlementRecommendation(
        scenario_id=batch_summary.get("scenario_id", "?"),
        scenario_title=batch_summary.get("scenario_title", "?"),
        n_runs=n,
        modal_outcome=modal_outcome,
        modal_outcome_meaning=_OUTCOME_MEANING.get(modal_outcome, "outcome meaning not documented"),
        confidence=confidence,
        dissenting_outcomes=dissenting,
        resolution_rate=resolution_rate,
        average_rounds_to_conclusion=metrics.get("average_rounds_to_conclusion", 0.0),
        rationale=" ".join(rationale_bits),
        sample_size_caveat=sample_size_caveat,
    )
